- name: Check The K8S Config Directory Whether Exist For All K8S Nodes
  stat:
    path: /etc/kubernetes/manifests
  register: kube_conf_path

- name: Install Kubernetes Software Package For All K8S Nodes
  yum:
    name:
    - kubeadm-{{ kube_ver }}
    - kubectl-{{ kube_ver }}
    - kubelet-{{ kube_ver }}
    - kubernetes-cni
    state: latest
  when: kube_conf_path.stat.isdir is not defined

- name: Enable Kubelet Service For All K8S Nodes
  systemd:
    name: kubelet
    enabled: yes
  ignore_errors: True 

- name: Configure Kubectl Command Line Auto Completion For All K8S Nodes
  shell: kubectl completion bash > /usr/share/bash-completion/completions/kubectl

- name: Reboot All The K8S Cluster Nodes
  reboot:
    connect_timeout:
