#- name: Query Docker Cgroup Driver Value
#  shell: docker info|grep 'Cgroup Driver'|awk '{print $3}'
#  register: docker_cgroup_driver

- name: Copy Kubeadm Config Template To Master1 Node
  template: src=kubeadm-config.yaml.j2 dest=/etc/kubernetes/kubeadm-config.yaml

- name: Pull Kubernetes Images By The Kubeadm Config File On Master1 Node
  shell: kubeadm config images pull --config=/etc/kubernetes/kubeadm-config.yaml
