- name: Fetch K8S Certificates From Master1 Node
  fetch:
    src: /tmp/k8s-cert/{{ item }}
    dest: /tmp/k8s-cert/
    flat: yes
  with_items:
  - ca-key.pem
  - apiserver.pem
  - apiserver-key.pem
  - apiserver-kubelet-client.pem
  - apiserver-kubelet-client-key.pem
  - front-proxy-ca.pem
  - front-proxy-ca-key.pem
  - front-proxy-client.pem
  - front-proxy-client-key.pem
  - sa.pub
  - sa.key
